version: "3"

services:
  mongo:
    image: mongo
    restart: unless-stopped

  reisekartet:
    image: ghcr.io/ldellisola/reisekartet:develop
    restart: unless-stopped
    environment:
      BING_MAPS_KEY: "..."
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017"
    ports:
      - 5000:80
